---
title: "PNG"
output: html_document
date: "2024-03-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(pdftools)
library(rnaturalearth)
library(wdpar)
```

# Data import from ARCGIS and rnaturalearth
```{r}
papua_n_g <- rnaturalearth::ne_countries(country = "papua new guinea", scale = "large") %>%
  select(name)

png_mpas <- wdpar::wdpa_fetch(x = "papua new guinea") %>%
  sf::st_transform(crs = st_crs(papua_n_g)) %>%
  sf::st_difference(st_difference(papua_n_g))

shp_PAI <- sf::st_read(dsn = "C:/Users/uqkgriha/Documents/Papoua New Guinea/Land-Sea - Priority Areas of Interest/") %>%
  sf::st_transform(crs = st_crs(papua_n_g)) %>%
  sf::st_difference(st_difference(papua_n_g))

shp_Top30_PA <- sf::st_read(dsn = "C:/Users/uqkgriha/Documents/Papoua New Guinea/Land-Sea - Top 30 Priority Areas/") %>%
  sf::st_transform(crs = st_crs(papua_n_g)) %>%
  sf::st_make_valid() %>%
  sf::st_difference(st_difference(papua_n_g)) 

shp_MarPOWPA <- sf::st_read(dsn = "C:/Users/uqkgriha/Documents/Papoua New Guinea/Marine POWPA - Difference in Selection Frequency/") %>%
  sf::st_transform(crs = st_crs(papua_n_g)) %>%
  sf::st_difference(st_difference(papua_n_g))
```

# NEW MPAS
### Conversion
```{r}
angle2dec <- function(angle) {
  angle <- gsub("°|'|\"", "", angle)
  x <- strsplit(angle, split=' ')
  x <- sapply(x, function(y) {
    y <- as.numeric(y)
    dec <- y[1] + y[2]/60 + y[3]/3600
    if (grepl("S|W", angle)) { 
      dec <- dec * -1
    }
    return(dec)
  })
  return(x)
}
```


## proposed MPAS
```{r, warning=FALSE}
data2polygon <- function(data) {
  data %>%
    dplyr::mutate(
      Longitude = sapply(Longitude, angle2dec),
      Latitude = sapply(Latitude, angle2dec)) %>%
    st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
    dplyr::summarize(do_union=FALSE) %>% 
    st_cast("POLYGON")
}
```

## proposed MPAs
```{r, warning=FALSE}
LYRES_REEF_NUGURIA_ISLAND <- data.frame(
  Points = 1:10,
  Latitude = c("3° 17' 23\" S", "4° 14' 58\" S", "4° 13' 21\" S", "2° 49' 13\" S", "2° 33' 41\" S",
               "1° 31' 30\" S", "1° 00' 52\" S", "0° 48' 39\" S", "0° 51' 15\" S", "1° 30' 27\" S"),
  Longitude = c("155° 40' 08\" E", "154° 30' 51\" E", "154° 04' 44\" E", "152° 58' 47\" E", "152° 38' 42\" E",
                 "152° 34' 36\" E", "153° 06' 00\" E", "153° 43' 04\" E", "154° 24' 31\" E", "154° 51' 54\" E"),
  Elev_m = c(-1616, -1264, -1888, -1159, -2178, -5725, -3938, -3736, -3186, -2331)
)

EAST_COAST_NAMATANAI <- data.frame(
  Points = 1:15,
  Latitude = c("3° 17' 23\" S", "4° 14' 58\" S", "4° 13' 21\" S", "2° 49' 13\" S", "2° 33' 41\" S",
               "2° 56' 46\" S", "3° 00' 36\" S", "3° 08' 47\" S", "3° 12' 36\" S", "3° 36' 02\" S",
               "3° 51' 53\" S", "4° 14' 15\" S", "4° 47' 18\" S", "4° 43' 00\" S", "4° 26' 35\" S"),
  Longitude = c("155° 40' 08\" E", "154° 30' 51\" E", "154° 04' 44\" E", "152° 58' 47\" E", "152° 38' 42\" E",
                 "151° 31' 31\" E", "151° 41' 55\" E", "151° 48' 28\" E", "152° 03' 14\" E", "152° 25' 05\" E",
                 "152° 48' 04\" E", "153° 06' 10\" E", "153° 26' 10\" E", "154° 14' 43\" E", "154° 33' 29\" E")
)

AROB <- data.frame(
  Points = 1:9,
  Latitude = c("3° 24' 28\" S", "4° 49' 50\" S", "4° 57' 21\" S", "5° 20' 57\" S", "5° 23' 17\" S",
               "5° 08' 21\" S", "4° 44' 52\" S", "4° 25' 16\" S", "4° 08' 28\" S"),
  Longitude = c("160° 29' 34\" E", "159° 58' 27\" E", "158° 52' 21\" E", "157° 05' 21\" E", "155° 32' 58\" E",
                 "155° 08' 58\" E", "154° 56' 44\" E", "154° 57' 34\" E", "155° 15' 27\" E"),
  Elev_m = c(-2344, -2237, -1877, -1488, -3083, -2535, -2788, -2872, -1867)
)
```

## designated MPA
```{r, warning=FALSE}
POCKLINGTON_REEF_MILNE_BAY_PROV <- data.frame(
  Points = 1:9,
  Latitude = c("11° 02' 30\" S", "10° 24' 44\" S", "10° 18' 32\" S", "10° 21' 33\" S", "10° 36' 58\" S",
                          "11° 14' 24\" S", "11° 27' 52\" S", "11° 23' 29\" S", "11° 12' 44\" S"),
  Longitude = c("154° 37' 13\" E", "155° 45' 08\" E", "155° 53' 55\" E", "156° 16' 31\" E", "156° 29' 59\" E",
                            "155° 52' 49\" E", "155° 06' 04\" E", "154° 47' 38\" E", "154° 38' 26\" E"))
```


```{r, warning=FALSE}
LYRES_REEF_NUGURIA_ISLAND <- data2polygon(LYRES_REEF_NUGURIA_ISLAND)
EAST_COAST_NAMATANAI <- data2polygon(EAST_COAST_NAMATANAI)
AROB <- data2polygon(AROB)
POCKLINGTON_REEF_MILNE_BAY_PROV <- data2polygon(POCKLINGTON_REEF_MILNE_BAY_PROV)
```


# Plot test 
```{r}
custom_theme <- theme_minimal() +
  theme(panel.background = element_rect(fill = "lightblue"))

PNGmap <- ggplot() +
  geom_sf(data = papua_n_g, fill = "white") +
  geom_sf(data = png_mpas, aes(fill = "Actual MPAs"), show.legend = "polygon") +
  geom_sf(data = shp_Top30_PA, alpha = 0.3, aes(fill = "Top 30 PA"), show.legend = "polygon") +
  geom_sf(data = shp_PAI, alpha = 0.3, aes(fill = "PAI"), show.legend = "polygon") +
  geom_sf(data = shp_MarPOWPA, alpha = 0.3, aes(fill = shp_MarPOWPA$Symb10b20), show.legend = "polygon") +
  geom_sf(data = LYRES_REEF_NUGURIA_ISLAND, aes(fill = "Lyres reef Nuguria"), show.legend = "polygon") +
  geom_sf(data = EAST_COAST_NAMATANAI, aes(fill = "East coast Namatanai"), show.legend = "polygon") +
  geom_sf(data = AROB, aes(fill = "Arob"), show.legend = "polygon") +
  geom_sf(data = POCKLINGTON_REEF_MILNE_BAY_PROV, aes(fill = "Pocklington Reef Milne Bay Prov"), show.legend = "polygon") +
  labs(title = "MPAs in Papua New Guinea",
       fill = "Legend") +
  # scale_fill_manual(values = c("red4", "blue", "green", "black"), 
  #                   labels = c("MPAs", "Top 30 PA", "PAI", "Pocklington Reef Milne Bay Prov"),
  #                   guide = guide_legend(title.position = "top", 
  #                                        title.hjust = 0.5,
  #                                        label.hjust = 0.5,
  #                                        label.position = "bottom",
  #                                        nrow = 4)) +
  custom_theme
  
# ggplot2::ggsave(filename = "C:/Users/uqkgriha/Documents/Papoua New Guinea/mapPNG.jpeg", dpi = 600)


```

# Data extraction
```{r}
texte_pdf <- pdftools::pdf_text("C:/Users/uqkgriha/Documents/Papoua New Guinea/MARINAS GUARDIANS PROPOSED SITEs 2024 with coordinatesMarch 24.pdf") 

```


# Fonction pour convertir une coordonnée DMS en décimal
```{r}
# Crée un dataframe pour stocker les coordonnées
coord_df <- data.frame(
  Points = integer(),
  Latitude = character(),
  Longitude = character(),
  Elevation = integer(),
  stringsAsFactors = FALSE
)

# Extrait les informations de chaque ligne et les ajoute au dataframe
lines <- strsplit(texte_pdf[2], "\n")[[1]] 

# Définir une fonction pour extraire le nom à partir des lignes
extract_name <- function(lines) {
  # Initialiser une chaîne vide pour stocker le nom
  name <- ""
  # Parcourir chaque ligne
  for (line in lines) {
    # Vérifier si la ligne contient uniquement des lettres
    if (grepl("^[a-zA-Z ]+$", line)) {
      # Si la ligne ne contient que des lettres, ajouter au nom
      name <- paste(name, line, collapse = " ")
    }
  }
  # Retourner le nom obtenu
  return(trimws(name))
}

# Extraire le nom
name <- extract_name(lines)
print(name)



# Parcourir chaque ligne à partir de la 14ème ligne (index 13) et extraire les informations pertinentes
for (i in 14:length(lines)) {
  # Séparer les éléments de chaque ligne en utilisant l'espace comme séparateur
  elements <- strsplit(lines[i], "\\s+")[[1]]
  # Ajouter les éléments au data frame
  coord_df <- rbind(coord_df, data.frame(
    Points = as.integer(elements[2]),
    Latitude = paste(elements[3], elements[4], elements[5], elements[6], sep = " "),
    Longitude = paste(elements[7], elements[8], elements[9], elements[10], sep = " "),
    Elevation = as.integer(elements[11]),
    Name = 
  ))
}

# Afficher le data frame
print(coord_df)
```




